apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-test-1-0223-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/test-1-0223
    newTag: dev-4510da91-20260223223339
