apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-test-1-0223-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: PLACEHOLDER_IMAGE_TAG
