apiVersion: v1
kind: Service
metadata:
  name: healthcp-test-0219
  labels:
    app: healthcp-test-0219
spec:
  selector:
    app: healthcp-test-0219
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
