apiVersion: v1
kind: Namespace
metadata:
  name: opsera-hcp-test-again-0220-dev
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: hcp-test-again-0220
    opsera.io/env: dev
