apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcp-test-again-0220
  namespace: opsera-hcp-test-again-0220-dev
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/app: hcp-test-again-0220
