apiVersion: v1
kind: Service
metadata:
  name: hcp-test-again-0220
  namespace: opsera-hcp-test-again-0220-dev
spec:
  selector:
    app: hcp-test-again-0220
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
