# ════════════════════════════════════════════════════════════════════════════
# Kustomize Overlay - dev environment
# ════════════════════════════════════════════════════════════════════════════
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-health-11-dev

resources:
  - ../../base
  - namespace.yaml

commonLabels:
  environment: dev
  tenant: opsera

patches:
  # Patch Ingress hostname
  - target:
      kind: Ingress
      name: health-11
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: opsera-health-11-dev.agent.opsera.dev

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
