apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcp-0209-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ORG_REPO
    path: .opsera-healthcp-0209/k8s/overlays/staging
    targetRevision: main
  destination:
    name: opsera-usw2-np
    namespace: opsera-healthcp-0209-staging
  syncPolicy:
    automated: null
    syncOptions:
      - Replace=true
