# RULE 149: destination.name (not server) | RULE 155: targetRevision = working branch
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcp-0209-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ORG_REPO
    path: .opsera-healthcp-0209/k8s/overlays/dev
    targetRevision: main
  destination:
    name: opsera-usw2-np
    namespace: opsera-healthcp-0209-dev
  syncPolicy:
    automated: null
    syncOptions:
      - Replace=true
