apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-4-0223
  namespace: opsera-test-4-0223-dev
  labels:
    app: test-4-0223
    environment: dev
    tenant: opsera
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: opsera-test-4-0223-dev.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-4-0223
                port:
                  number: 80
