apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-test-4-0223-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/test-4-0223
    newTag: dev-0f9b8760-20260223235112
