apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcp-0212
  labels:
    app: healthcp-0212
spec:
  ingressClassName: nginx
  rules:
    - host: healthcp-0212-dev.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcp-0212
                port:
                  number: 8080
  # tls can be added when cert-manager/ACM is configured
