apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcp-test-0219-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Opsera-Test/healthcp
    targetRevision: main
    path: .opsera-hcp-test-0219/k8s/overlays/uat
  destination:
    name: opsera-usw2-np
    namespace: opsera-hcp-test-0219-uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
