apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcp-0208-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-agentic/healthcp
    path: .opsera-hcp-0208/k8s/overlays/dev
    targetRevision: main
  destination:
    name: opsera-usw2-np
    namespace: opsera-hcp-0208-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
