apiVersion: v1
kind: Service
metadata:
  name: hcp-0223
  labels:
    app: hcp-0223
    tenant: opsera
spec:
  selector:
    app: hcp-0223
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
