apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-hcp-0207-dev
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
replicas:
  - name: hcp-0207
    count: 1
