apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-hcp-0207-dev
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
images:
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/hcp-0207
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/hcp-0207
    newTag: 35bee89
replicas:
  - name: hcp-0207
    count: 1
