apiVersion: v1
kind: Namespace
metadata:
  name: opsera-healthcp-test-0223-e5742-dev
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: healthcp-test-0223-e5742
    opsera.io/env: dev
