apiVersion: v1
kind: Service
metadata:
  name: healthcp-test-0223-e5742
  namespace: opsera-healthcp-test-0223-e5742-dev
  labels:
    app: healthcp-test-0223-e5742
    tenant: opsera
spec:
  type: ClusterIP
  selector:
    app: healthcp-test-0223-e5742
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
