apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcp-test-0223-e5742
  namespace: opsera-healthcp-test-0223-e5742-dev
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: healthcp-test-0223-e5742
