apiVersion: v1
kind: Namespace
metadata:
  name: opsera-healthcp-test-0220-725d6-uat
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: healthcp-test-0220-725d6
    opsera.io/env: uat
