apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcp-test-0220-725d6
  namespace: opsera-healthcp-test-0220-725d6-uat
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/app: healthcp-test-0220-725d6
