apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-test-3-0223-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/test-3-0223
    newTag: dev-bf8ec29c-20260223232859
