apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcp-test-again-0220
  namespace: opsera-hcp-test-again-0220-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: hcp-test-again-0220.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcp-test-again-0220
                port:
                  number: 80
