# Opsera Code-to-Cloud config - Quick Setup
app_name: hcp-0208
tenant: opsera
region: us-west-2
region_short: usw2
spoke_cluster: opsera-usw2-np
hub_cluster: argocd-usw2
argocd_server: argocd-usw2.agent.opsera.dev
domain: agent.opsera.dev
environments:
  - dev
