apiVersion: v1
kind: Namespace
metadata:
  name: opsera-hcp-test-0219-uat
  labels:
    app.kubernetes.io/managed-by: opsera
    opsera.io/tenant: opsera
    opsera.io/app: hcp-test-0219
    opsera.io/env: uat
