apiVersion: v1
kind: Service
metadata:
  name: hcp-test-0219
  namespace: opsera-hcp-test-0219-uat
spec:
  selector:
    app: hcp-test-0219
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
