apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-hcp-0223-dev

resources:
  - ../../base
  - namespace.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/hcp-0223
    newTag: dev-ca4615a9-20260223220035
