apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-hcp-0223-dev

resources:
  - ../../base
  - namespace.yaml
  - deployment.yaml
  - serviceaccount.yaml

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      tenant: opsera

images:
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/hcp-0223
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/hcp-0223
    newTag: dev-34036f1c-20260223213714
