apiVersion: v1
kind: Service
metadata:
  name: test-3-0223
  labels:
    app: test-3-0223
    managed-by: opsera-c2c
spec:
  selector:
    app: test-3-0223
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
