apiVersion: v1
kind: Service
metadata:
  name: health-6-0223
  labels:
    app: health-6-0223
    managed-by: opsera-c2c
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app: health-6-0223
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
