apiVersion: v1
kind: Service
metadata:
  name: test-2
  labels:
    app: test-2
    managed-by: opsera-c2c
spec:
  selector:
    app: test-2
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
