apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcp-test-0223-e5742
  namespace: opsera-healthcp-test-0223-e5742-dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: healthcp-test-0223-e5742.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcp-test-0223-e5742
                port:
                  number: 80
