apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-healthcp-test-0223-e5742-dev
resources:
  - ../../base
  - ingress.yaml
labels:
  - pairs:
      environment: dev
      tenant: opsera
    includeSelectors: false
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: healthcp-test-0223-e5742
