apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-health-6-0223-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: PLACEHOLDER_IMAGE_TAG
