# Staging: Blue-Green (RULE 106: includeSelectors: false)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-healthcp-0209-staging
resources:
  - ../../base
  - rollout-bluegreen.yaml
  - services-bluegreen.yaml
  - analysis-template.yaml
labels:
  - pairs:
      app: healthcp-0209
      env: staging
    includeSelectors: false
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: healthcp-0209
