apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcp-test-0219
  namespace: opsera-hcp-test-0219-uat
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: hcp-test-0219.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcp-test-0219
                port:
                  number: 80
