apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-1-role
  labels:
    app: test-1
    managed-by: opsera-c2c
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-1-rolebinding
  labels:
    app: test-1
    managed-by: opsera-c2c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-1-role
subjects:
  - kind: ServiceAccount
    name: test-1
